version: "3"

services:

  smashing:
    container_name: smashing
    image: lucapxl/smashing
    restart: unless-stopped
    ports:
      - 3030:3030
    environment:
      - GEMS=json
    volumes:
      - /home/pixel/smashing/:/smashing/
